[application]
name = "client"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "client"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
